NAME = "name"
BASELINE_YEAR = "baseline_year"
TARGET_YEAR = "target_year"
WAY_POINTS = "waypoints"

CO2E = "co2e"
AREA = "area"
PROTEIN = "protein"
BIO_ENERGY = "bio_energy"
HWP = "hwp"
SUBSTITUTION = "substitution"
BIODIVERSITY = "biodiversity"

HNV_AREA = "hnv_area"

FORESTRY = "forestry"
FORESTRY_AFFORESTATION = "afforestation"
FORESTRY_EXISTING_FOREST = "existing_forest"
AFFORESTATION_ORGANIC_SOIL_AREA = "organic_soil_area"

ORGANIC_SOILS = "organic_soils"
ORGANIC_SOILS_DRAINAGE_STATUS = "drainage_status"
ORGANIC_SOILS_ORGANIC_SOIL_UNDER_GRASS = "Organic soil under grass"
ORGANIC_SOILS_NEAR_NATURAL_WETLANDS = "Near natural wetlands"
ORGANIC_SOILS_INDUSTRIAL_PEAT = "Industrial peat"
ORGANIC_SOILS_DOMESTIC_PEAT = "Domestic peat"
DRAINED = "Drained"
REWETTED = "Rewetted"

NON_CATTLE_AGRICULTURE = "non_cattle_agriculture"
NON_CATTLE_AGRICULTURE_PIGS = "Pigs"
NON_CATTLE_AGRICULTURE_POULTRY = "Poultry"
NON_CATTLE_AGRICULTURE_SHEEP = "Sheep"
NON_CATTLE_AGRICULTURE_CROPS = "Crops"
NON_CATTLE_AGRICULTURE_NO_CROPS = "No-Crops"

CATTLE_AGRICULTURE = "cattle_systems"
CATTLE_AGRICULTURE_BEEF = "Beef"
CATTLE_AGRICULTURE_DAIRY = "Dairy"
CATTLE_AGRICULTURE_PROTEIN_MILK = "protein_milk"
CATTLE_AGRICULTURE_PROTEIN_BEEF = "protein_beef"
CATTLE_AGRICULTURE_SPARED_AREA = "Spared Cattle/Sheep area"
DAIRY_AREA = "area_dairy"
BEEF_AREA = "area_beef"

AGRICULTURE_BASELINE_ABATEMENT = "abatement"
AGRICULTURE_BASELINE_PRODUCTIVITY = "productivity"

TABLE_NON_CATTLE="non_cattle"
TABLE_CATTLE="cattle"

AD_EMISSIONS = "ad_emissions"
AD_ADDITIONAL_AREA = "additional_area"
AD_WILLOW_AREA = "willow_area"